[package]
name = "rod"
version = "0.1.1"
edition = "2024"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
clap-markdown = "0.1.4"
console = "0.15.11"
dirs = "6.0.0"
serde = { version = "1.0.217", features = ["serde_derive"] }
toml = "0.8.19"


[profile.release]
opt-level = 3
strip = true
lto = true
panic = "abort"
codegen-units = 1
