[package]
name = "rod"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
console = "0.15.11"
dirs = "6.0.0"
serde = { version = "1.0.217", features = ["serde_derive"] }
toml = "0.8.19"
